/* Generated by @deepseek-ai/dsh-typert-generator from the Host FaceModel — do not edit. */
import type {
  RemoteResult,
  TypertRemoteContribution,
} from '@deepseek-ai/dsh-typert-protocol'
import type { XiangqiMoveRequest, XiangqiNewGameRequest, XiangqiResignRequest, XiangqiSerializedState, XiangqiUndoRequest } from '@deepseek-ai/dsh-plugin-xiangqi/types'
import type { SessionId } from '@deepseek-ai/dsh-session/types'

declare module '@deepseek-ai/dsh-typert-protocol' {
  interface TypertRemoteNamespace$7869616e677169 {
    get: (agentId: SessionId, gameId?: string) => Promise<RemoteResult<XiangqiSerializedState>>
    move: (agentId: SessionId, request: XiangqiMoveRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    newGame: (agentId: SessionId, _request?: XiangqiNewGameRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    resign: (agentId: SessionId, request: XiangqiResignRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    undo: (agentId: SessionId, request: XiangqiUndoRequest) => Promise<RemoteResult<XiangqiSerializedState>>
  }
  interface TypertRemoteMap {
    'xiangqi/get': (agentId: SessionId, gameId?: string) => Promise<RemoteResult<XiangqiSerializedState>>
    'xiangqi/move': (agentId: SessionId, request: XiangqiMoveRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'xiangqi/newGame': (agentId: SessionId, _request?: XiangqiNewGameRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'xiangqi/resign': (agentId: SessionId, request: XiangqiResignRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'xiangqi/undo': (agentId: SessionId, request: XiangqiUndoRequest) => Promise<RemoteResult<XiangqiSerializedState>>
  }
  interface TypertRemoteNamespaceMap {
    'xiangqi': TypertRemoteNamespace$7869616e677169
  }
  interface TypertRemoteScopeMap {
    'agent:xiangqi/get': (gameId?: string) => Promise<RemoteResult<XiangqiSerializedState>>
    'agent:xiangqi/move': (request: XiangqiMoveRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'agent:xiangqi/newGame': (_request?: XiangqiNewGameRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'agent:xiangqi/resign': (request: XiangqiResignRequest) => Promise<RemoteResult<XiangqiSerializedState>>
    'agent:xiangqi/undo': (request: XiangqiUndoRequest) => Promise<RemoteResult<XiangqiSerializedState>>
  }
}

export declare const TYPERT_REMOTE: TypertRemoteContribution
export default TYPERT_REMOTE
//# sourceMappingURL=typert.remote-client.d.ts.map
