/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)), z.array(z.lazy(() => JsonValueRemoteCodec$schema))])
const JsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)), z.array(z.lazy(() => JsonValueRemoteCodec$schema2))])
const JsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3)), z.array(z.lazy(() => JsonValueRemoteCodec$schema3))])
const JsonValueRemoteCodec$schema4 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4)), z.array(z.lazy(() => JsonValueRemoteCodec$schema4))])
const JsonValueRemoteCodec$schema5 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5)), z.array(z.lazy(() => JsonValueRemoteCodec$schema5))])
const JsonValueRemoteCodec$schema6 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema6)), z.array(z.lazy(() => JsonValueRemoteCodec$schema6))])
const JsonValueRemoteCodec$schema7 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema7)), z.array(z.lazy(() => JsonValueRemoteCodec$schema7))])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_cancelAiMove_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_cancelAiMove_result$schema = z.object({
  'cancelled': z.boolean().readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_1$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3)), z.array(z.lazy(() => JsonValueRemoteCodec$schema3))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_parameter_1$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_result$schema = z.union([z.literal(null), z.object({
  'decisionId': z.string().readonly(),
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("preparing"), z.literal("requesting"), z.literal("receiving"), z.literal("validating"), z.literal("committing"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]).readonly(),
  'phaseText': z.string().readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'reasoningEffort': z.string().readonly(),
  'elapsedMs': z.number().readonly(),
  'outputChars': z.number().readonly(),
  'reasoningDeltaCount': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.number().readonly(),
  'speaker': z.union([z.literal("host"), z.literal("dsh")]).readonly(),
  'kind': z.union([z.literal("status"), z.literal("request"), z.literal("response"), z.literal("error")]).readonly(),
  'text': z.string().readonly(),
  'elapsedMs': z.number().readonly(),
})).readonly(),
})])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getRuntimeState_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getRuntimeState_result$schema = z.object({
  'state': z.union([z.literal(null), z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)), z.array(z.lazy(() => JsonValueRemoteCodec$schema))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})]).readonly(),
  'aiPending': z.boolean().readonly(),
  'phase': z.union([z.literal(null), z.literal("preparing"), z.literal("requesting"), z.literal("receiving"), z.literal("validating"), z.literal("committing"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]).readonly(),
  'trace': z.union([z.literal(null), z.object({
  'decisionId': z.string().readonly(),
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("preparing"), z.literal("requesting"), z.literal("receiving"), z.literal("validating"), z.literal("committing"), z.literal("completed"), z.literal("failed"), z.literal("cancelled")]).readonly(),
  'phaseText': z.string().readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'reasoningEffort': z.string().readonly(),
  'elapsedMs': z.number().readonly(),
  'outputChars': z.number().readonly(),
  'reasoningDeltaCount': z.number().readonly(),
  'entries': z.array(z.object({
  'id': z.number().readonly(),
  'speaker': z.union([z.literal("host"), z.literal("dsh")]).readonly(),
  'kind': z.union([z.literal("status"), z.literal("request"), z.literal("response"), z.literal("error")]).readonly(),
  'text': z.string().readonly(),
  'elapsedMs': z.number().readonly(),
})).readonly(),
})]).readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'move': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4)), z.array(z.lazy(() => JsonValueRemoteCodec$schema4))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_1$schema = z.object({
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)), z.array(z.lazy(() => JsonValueRemoteCodec$schema2))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'modelOverride': z.union([z.undefined(), z.object({
  'provider': z.union([z.undefined(), z.string()]).readonly().optional(),
  'model': z.union([z.undefined(), z.string()]).readonly().optional(),
  'reasoningEffort': z.union([z.undefined(), z.string()]).readonly().optional(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_result$schema = z.union([z.object({
  'status': z.literal("moved").readonly(),
  'state': z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema7)), z.array(z.lazy(() => JsonValueRemoteCodec$schema7))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
}).readonly(),
  'decision': z.object({
  'source': z.literal("dsh").readonly(),
  'decisionId': z.string().readonly(),
  'provider': z.string().readonly(),
  'model': z.string().readonly(),
  'candidateId': z.string().readonly(),
  'revision': z.number().readonly(),
  'latencyMs': z.number().readonly(),
  'summary': z.union([z.undefined(), z.string()]).readonly().optional(),
}).readonly(),
}), z.object({
  'status': z.literal("failed").readonly(),
  'code': z.union([z.literal("MODEL_ERROR"), z.literal("INVALID_DECISION"), z.literal("DECISION_CANCELLED"), z.literal("DECISION_IN_PROGRESS"), z.literal("STALE_GAME"), z.literal("STALE_REVISION"), z.literal("NOT_BLACK_TURN")]).readonly(),
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'message': z.string().readonly(),
}), z.object({
  'status': z.literal("stale").readonly(),
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'message': z.string().readonly(),
})])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'side': z.union([z.literal("red"), z.literal("black")]).readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema6)), z.array(z.lazy(() => JsonValueRemoteCodec$schema6))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.union([z.undefined(), z.string()]).readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.undefined(), z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5)), z.array(z.lazy(() => JsonValueRemoteCodec$schema5))]).readonly(),
  'lastMove': z.union([z.undefined(), z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
})]).readonly().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-plugin-xiangqi',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/cancelAiMove',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'cancelAiMove',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_cancelAiMove_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/cancelAiMove:result',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_cancelAiMove_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":243,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/get',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'get',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_0$schema,
          },
        },
        {
          name: 'gameId',
          wire: 'gameId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/get:gameId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":194,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/getDecisionTrace',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'getDecisionTrace',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_parameter_0$schema,
          },
        },
        {
          name: 'gameId',
          wire: 'gameId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/getDecisionTrace:gameId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/getDecisionTrace:result',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getDecisionTrace_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":206,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/getRuntimeState',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'getRuntimeState',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getRuntimeState_parameter_0$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiRuntimeState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_getRuntimeState_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":162,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/move',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'move',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiMoveRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":215,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/newGame',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'newGame',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_0$schema,
          },
        },
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiNewGameRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":178,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/requestAiMove',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'requestAiMove',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiAiTurnRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiAiTurnResult',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_requestAiMove_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":249,"column":9},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/resign',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'resign',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiResignRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":234,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/undo',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'undo',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiUndoRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_result$schema,
      },
      sourceLocation: {"file":"packages/xiangqi/src/host/dsh-service.ts","line":225,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host-side service loaded by the bundle patch. Every Remote method starts with Agent so Typert maps the client SessionId to the exact live agent.",
        "summary": "Host-side service loaded by the bundle patch.",
        "tags": [],
        "jsDoc": "/**\n * Host-side service loaded by the bundle patch. Every Remote method starts\n * with Agent so Typert maps the client SessionId to the exact live agent.\n */",
        "key": "xiangqi",
        "exportName": "XiangqiService",
        "members": [
          {
            "kind": "method",
            "name": "getRuntimeState",
            "signature": "@Remote('getRuntimeState') getRuntimeState(agent: Agent): XiangqiRuntimeState",
            "summary": "原子读取 Host 运行状态（审查第二轮 P1）：任意标签页一次调用即可拿到 当前棋局、\"Host 是否真的有决策在跑\"与决策追踪，不再依赖本页面自己 发起的请求来猜测全局状态。",
            "jsDoc": "/**\n * 原子读取 Host 运行状态（审查第二轮 P1）：任意标签页一次调用即可拿到\n * 当前棋局、\"Host 是否真的有决策在跑\"与决策追踪，不再依赖本页面自己\n * 发起的请求来猜测全局状态。\n */"
          },
          {
            "kind": "method",
            "name": "newGame",
            "signature": "@Remote('newGame') newGame(agent: Agent, _request: XiangqiNewGameRequest): XiangqiSerializedState",
            "summary": "Start one new global game; switching chats never creates one implicitly.",
            "jsDoc": "/** Start one new global game; switching chats never creates one implicitly. */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(agent: Agent, gameId?: string): XiangqiSerializedState",
            "summary": "Read the one process-global game.",
            "jsDoc": "/**\n * Read the one process-global game. The first read creates the initial game\n * when this DSH Host has no game yet; switching chats only reads this same\n * game and never creates another one.\n */"
          },
          {
            "kind": "method",
            "name": "getDecisionTrace",
            "signature": "@Remote('getDecisionTrace') getDecisionTrace(agent: Agent, gameId?: string): XiangqiDecisionTrace | null",
            "summary": "Read the latest non-durable DSH decision trace for the process-global game.",
            "jsDoc": "/** Read the latest non-durable DSH decision trace for the process-global game. */"
          },
          {
            "kind": "method",
            "name": "move",
            "signature": "@Remote('move') move(agent: Agent, request: XiangqiMoveRequest): XiangqiSerializedState",
            "summary": "Apply one revision-fenced move.",
            "jsDoc": "/** Apply one revision-fenced move. */"
          },
          {
            "kind": "method",
            "name": "undo",
            "signature": "@Remote('undo') undo(agent: Agent, request: XiangqiUndoRequest): XiangqiSerializedState",
            "summary": "Undo one committed move.",
            "jsDoc": "/** Undo one committed move. */"
          },
          {
            "kind": "method",
            "name": "resign",
            "signature": "@Remote('resign') resign(agent: Agent, request: XiangqiResignRequest): XiangqiSerializedState",
            "summary": "Mark one side as resigned.",
            "jsDoc": "/** Mark one side as resigned. */"
          },
          {
            "kind": "method",
            "name": "cancelAiMove",
            "signature": "@Remote('cancelAiMove') cancelAiMove(agent: Agent): { readonly cancelled: boolean }",
            "summary": "Cancel the in-flight lightweight DSH decision without changing the game revision.",
            "jsDoc": "/** Cancel the in-flight lightweight DSH decision without changing the game revision. */"
          },
          {
            "kind": "method",
            "name": "requestAiMove",
            "signature": "@Remote('requestAiMove') async requestAiMove(agent: Agent, request: XiangqiAiTurnRequest): Promise<XiangqiAiTurnResult>",
            "summary": "Ask the selected DSH model for one frozen-candidate decision, then commit it.",
            "jsDoc": "/** Ask the selected DSH model for one frozen-candidate decision, then commit it. */"
          }
        ],
        "types": [
          {
            "name": "Agent",
            "declaration": "export interface Agent {\n    readonly id: SessionId;\n    readonly options: AgentOptions;\n    readonly session: Session;\n    readonly inbox: Inbox;\n    readonly status: AgentStatus;\n    readonly ctx: Context;\n    cancel(cause: AgentCancelCause, options?: CancelOptions): void;\n    whenIdle(): Promise<void>;\n    runMaintenance<T>(task: (signal: AbortSignal) => Promise<T>): Promise<T>;\n    send(message: UserMessage, target: InboxTarget, wakeup: boolean): void;\n    followup(message: UserMessage): void;\n    steer(message: UserMessage): void;\n    inject(message: UserMessage): void;\n}"
          },
          {
            "name": "AgentCancelCause",
            "declaration": "export type AgentCancelCause = { readonly kind: 'user'; } | { readonly kind: 'parent'; } | { readonly kind: 'hook'; readonly reason: string; } | { readonly kind: 'disposed'; };"
          },
          {
            "name": "AgentOptions",
            "declaration": "export interface AgentOptions {\n    provider?: string;\n    model?: string;\n    reasoningEffort?: ReasoningEffortId;\n    maxTokens?: number;\n}"
          },
          {
            "name": "AgentStatus",
            "declaration": "export type AgentStatus = 'idle' | 'running';"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "BrandedNumber",
            "declaration": "export type BrandedNumber<B extends string> = number & { readonly [BRAND]: B; };"
          },
          {
            "name": "CancelOptions",
            "declaration": "export interface CancelOptions {\n    keepInbox?: boolean | undefined;\n}"
          },
          {
            "name": "EpochHeader",
            "declaration": "export interface EpochHeader {\n    config: LlmCallConfig;\n    adapterDefaults?: LlmCallConfigAdapterDefaults;\n    tools?: ToolSchema[];\n}"
          },
          {
            "name": "Inbox",
            "declaration": "export interface Inbox {\n    readonly nextTurn: readonly UserMessage[];\n    readonly nextStep: readonly UserMessage[];\n    clear(): void;\n    append(target: InboxTarget, message: UserMessage): void;\n    prepend(target: InboxTarget, message: UserMessage): void;\n    replace(messageId: MessageId, newMessage: UserMessage): boolean;\n    remove(messageId: MessageId): boolean;\n    splice(target: InboxTarget, start: number, deleteCount: number, inserted: UserMessage[]): UserMessage[];\n}"
          },
          {
            "name": "InboxTarget",
            "declaration": "export type InboxTarget = 'next-turn' | 'next-step';"
          },
          {
            "name": "JsonObject",
            "declaration": "export interface JsonObject {\n    [key: string]: JsonValue;\n}"
          },
          {
            "name": "JsonPrimitive",
            "declaration": "export type JsonPrimitive = string | number | boolean | null;"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];"
          },
          {
            "name": "ModelSelection",
            "declaration": "export interface ModelSelection {\n    readonly provider: string;\n    readonly model: string;\n    readonly reasoningEffort?: string;\n}"
          },
          {
            "name": "RequestContext",
            "declaration": "export interface RequestContext {\n    provider: string;\n    model: string;\n    contextWindow?: number;\n    systemPromptUpdate?: SystemPromptUpdate;\n}"
          },
          {
            "name": "RequestHeaderReason",
            "declaration": "export type RequestHeaderReason = 'initial' | 'resume' | 'change' | 'series';"
          },
          {
            "name": "Session",
            "declaration": "export class Session {\n    get surface(): SessionSurface;\n    readonly header: SessionHeader;\n    readonly inheritedEventCount: SessionLogOffset;\n    get id(): SessionId;\n    readonly firstLiveSeq: SessionLogOffset;\n    eventAt(seq: SessionSeq): SessionEvent | undefined;\n    snapshotEvents(fromSeq?: SessionLogOffset, toSeqExclusive?: SessionLogOffset): readonly SessionEvent[];\n    ownEvents(): readonly SessionEvent[];\n    isOwnSeq(seq: SessionSeq): boolean;\n    get seq(): SessionLogOffset;\n    append<T extends SessionEventType>(type: T, data: SessionEventMap[T], ...opts: T extends SurfaceEventType ? [opts: SurfaceIntent<T>] : []): SessionEvent<T>;\n    requestHeader(): EpochHeader | undefined;\n    requestContext(): RequestContext | undefined;\n    deriveMessages(): Message[];\n    deriveEventMessage(event: SessionEvent): Message | null;\n}"
          },
          {
            "name": "SessionEvent",
            "declaration": "export type SessionEvent<T extends SessionEventType = SessionEventType> = { [K in SessionEventType]: { type: K; seq: SessionSeq; time: number; data: SessionEventMap[K]; ignorable?: true; } & (K extends SurfaceEventType ? SurfaceIntent<K> : { surfaceOp?: never; sourceEventSeqs?: never; }) }[T];"
          },
          {
            "name": "SessionEventMap",
            "declaration": "export interface SessionEventMap {\n    'turn/start': { turn: number; };\n    'turn/end': { turn: number; reason: TurnEndReason; };\n    'step/start': { turn: number; step: number; };\n    'step/end': { turn: number; step: number; };\n    'user/message': UserMessage;\n    'system/message': { turn: number; step: number; message: SystemMessage; };\n    'assistant/message': { turn: number; step: number; message: AssistantMessage; stream: AssistantStreamRecord[]; usage?: TokenUsage; interrupted?: true; };\n    'assistant/attempt': { turn: number; step: number; stream: AssistantStreamRecord[]; };\n    'tool/call': { turn: number; step: number; callId: ToolCallId; name: string; arguments: string; };\n    'tool/result': { turn: number; step: number; message: ToolResultMessage; error?: { name: string; code: string; }; meta?: JsonValue; };\n    'request/header': { header: EpochHeader; reason: RequestHeaderReason; startsSeries?: true; };\n    'request/context': RequestContext;\n    'session/end-seed': { inherited?: true; };\n    'agent/inbox/spliced': { target: InboxTarget; start: number; removedCount?: number; inserted: UserMessage[]; outcome?: 'canceled'; };\n    'model/selection': ModelSelection;\n    'xiangqi/change': XiangqiChange;\n}"
          },
          {
            "name": "SessionEventType",
            "declaration": "export type SessionEventType = keyof SessionEventMap;"
          },
          {
            "name": "SessionHeader",
            "declaration": "export interface SessionHeader {\n    readonly version: typeof SESSION_FORMAT_VERSION;\n    readonly id: SessionId;\n    readonly createdAt: number;\n    readonly cwd?: string;\n    readonly parentSession?: SessionId;\n    readonly isSeeded: boolean;\n    readonly origin?: 'subagent';\n    readonly delegationDepth?: number;\n    readonly agentPreset?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SessionLogOffset",
            "declaration": "export type SessionLogOffset = BrandedNumber<'SessionLogOffset'>;"
          },
          {
            "name": "SessionSeq",
            "declaration": "export type SessionSeq = BrandedNumber<'SessionSeq'>;"
          },
          {
            "name": "SessionSurface",
            "declaration": "export interface SessionSurface {\n    readonly nodes: readonly SessionSeq[];\n    readonly replaceGeneration: number;\n}"
          },
          {
            "name": "SurfaceEventType",
            "declaration": "export type SurfaceEventType = 'system/message' | 'user/message' | 'assistant/message' | 'tool/result';"
          },
          {
            "name": "SurfaceIntent",
            "declaration": "export type SurfaceIntent<T extends SurfaceEventType = SurfaceEventType> = { surfaceOp: SurfaceOp; } & (T extends 'assistant/message' ? { sourceEventSeqs?: never; } : { sourceEventSeqs?: SessionSeq[]; });"
          },
          {
            "name": "SurfaceOp",
            "declaration": "export type SurfaceOp = 'append' | { op: 'replace'; startSeq: SessionSeq; endSeq: SessionSeq; };"
          },
          {
            "name": "TurnEndCancelCause",
            "declaration": "export type TurnEndCancelCause = AgentCancelCause | { readonly kind: 'legacy'; };"
          },
          {
            "name": "TurnEndReason",
            "declaration": "export type TurnEndReason = TurnEndReasonMap[keyof TurnEndReasonMap];"
          },
          {
            "name": "TurnEndReasonMap",
            "declaration": "export interface TurnEndReasonMap {\n    completed: { kind: 'completed'; };\n    aborted: { kind: 'aborted'; reason: TurnEndCancelCause; };\n    blocked: { kind: 'blocked'; };\n    error: { kind: 'error'; error: LlmFailure; };\n    'max-tokens': { kind: 'max-tokens'; };\n    interrupted: { kind: 'interrupted'; };\n}"
          },
          {
            "name": "XiangqiAiModelOverride",
            "declaration": "export interface XiangqiAiModelOverride {\n    readonly provider?: string;\n    readonly model?: string;\n    readonly reasoningEffort?: XiangqiAiReasoningEffort;\n}"
          },
          {
            "name": "XiangqiAiReasoningEffort",
            "declaration": "export type XiangqiAiReasoningEffort = string;"
          },
          {
            "name": "XiangqiAiTurnFailureCode",
            "declaration": "export type XiangqiAiTurnFailureCode = 'MODEL_ERROR' | 'INVALID_DECISION' | 'DECISION_CANCELLED' | 'DECISION_IN_PROGRESS' | 'STALE_GAME' | 'STALE_REVISION' | 'NOT_BLACK_TURN';"
          },
          {
            "name": "XiangqiAiTurnRequest",
            "declaration": "export interface XiangqiAiTurnRequest {\n    readonly gameId: string;\n    readonly revision: number;\n    readonly modelOverride?: XiangqiAiModelOverride;\n}"
          },
          {
            "name": "XiangqiAiTurnResult",
            "declaration": "export type XiangqiAiTurnResult = { readonly status: 'moved'; readonly state: XiangqiSerializedState; readonly decision: XiangqiDecisionMeta; } | { readonly status: 'failed'; readonly code: XiangqiAiTurnFailureCode; readonly gameId: string; readonly revision: number; readonly message: string; } | { readonly status: 'stale'; readonly gameId: string; readonly revision: number; readonly message: string; };"
          },
          {
            "name": "XiangqiChange",
            "declaration": "export interface XiangqiChange {\n    readonly operation: XiangqiOperation;\n    readonly state: XiangqiSerializedState;\n    readonly decision?: XiangqiDecisionMeta;\n}"
          },
          {
            "name": "XiangqiDecisionMeta",
            "declaration": "export interface XiangqiDecisionMeta {\n    readonly source: 'dsh';\n    readonly decisionId: string;\n    readonly provider: string;\n    readonly model: string;\n    readonly candidateId: string;\n    readonly revision: number;\n    readonly latencyMs: number;\n    readonly summary?: string;\n}"
          },
          {
            "name": "XiangqiDecisionTrace",
            "declaration": "export interface XiangqiDecisionTrace {\n    readonly decisionId: string;\n    readonly gameId: string;\n    readonly revision: number;\n    readonly phase: XiangqiDecisionTracePhase;\n    readonly phaseText: string;\n    readonly provider: string;\n    readonly model: string;\n    readonly reasoningEffort: XiangqiAiReasoningEffort;\n    readonly elapsedMs: number;\n    readonly outputChars: number;\n    readonly reasoningDeltaCount: number;\n    readonly entries: readonly XiangqiDecisionTraceEntry[];\n}"
          },
          {
            "name": "XiangqiDecisionTraceEntry",
            "declaration": "export interface XiangqiDecisionTraceEntry {\n    readonly id: number;\n    readonly speaker: 'host' | 'dsh';\n    readonly kind: 'status' | 'request' | 'response' | 'error';\n    readonly text: string;\n    readonly elapsedMs: number;\n}"
          },
          {
            "name": "XiangqiDecisionTracePhase",
            "declaration": "export type XiangqiDecisionTracePhase = 'preparing' | 'requesting' | 'receiving' | 'validating' | 'committing' | 'completed' | 'failed' | 'cancelled';"
          },
          {
            "name": "XiangqiGamePhase",
            "declaration": "export type XiangqiGamePhase = 'active' | 'resigned';"
          },
          {
            "name": "XiangqiMove",
            "declaration": "export interface XiangqiMove {\n    readonly from: string;\n    readonly to: string;\n}"
          },
          {
            "name": "XiangqiMoveRequest",
            "declaration": "export interface XiangqiMoveRequest {\n    readonly gameId: string;\n    readonly revision: number;\n    readonly move: XiangqiMove;\n}"
          },
          {
            "name": "XiangqiNewGameRequest",
            "declaration": "export interface XiangqiNewGameRequest {\n    readonly sessionId?: string;\n}"
          },
          {
            "name": "XiangqiOperation",
            "declaration": "export type XiangqiOperation = 'newGame' | 'move' | 'undo' | 'resign';"
          },
          {
            "name": "XiangqiResignRequest",
            "declaration": "export interface XiangqiResignRequest {\n    readonly gameId: string;\n    readonly revision: number;\n    readonly side: XiangqiSide;\n}"
          },
          {
            "name": "XiangqiRuntimeState",
            "declaration": "export interface XiangqiRuntimeState {\n    readonly state: XiangqiSerializedState | null;\n    readonly aiPending: boolean;\n    readonly phase: XiangqiDecisionTracePhase | null;\n    readonly trace: XiangqiDecisionTrace | null;\n}"
          },
          {
            "name": "XiangqiSerializedState",
            "declaration": "export interface XiangqiSerializedState {\n    readonly gameId: string;\n    readonly sessionId?: string;\n    readonly revision: number;\n    readonly phase: XiangqiGamePhase;\n    readonly winner?: XiangqiSide;\n    readonly gameState: JsonValue;\n    readonly lastMove?: XiangqiMove;\n}"
          },
          {
            "name": "XiangqiSide",
            "declaration": "export type XiangqiSide = 'red' | 'black';"
          },
          {
            "name": "XiangqiUndoRequest",
            "declaration": "export interface XiangqiUndoRequest {\n    readonly gameId: string;\n    readonly revision: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
