/* Generated by @deepseek-ai/dsh-typert-generator from FaceModel — do not edit. */
import { z } from 'zod'

const JsonValueRemoteCodec$schema = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)), z.array(z.lazy(() => JsonValueRemoteCodec$schema))])
const JsonValueRemoteCodec$schema2 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)), z.array(z.lazy(() => JsonValueRemoteCodec$schema2))])
const JsonValueRemoteCodec$schema3 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3)), z.array(z.lazy(() => JsonValueRemoteCodec$schema3))])
const JsonValueRemoteCodec$schema4 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4)), z.array(z.lazy(() => JsonValueRemoteCodec$schema4))])
const JsonValueRemoteCodec$schema5 = z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5)), z.array(z.lazy(() => JsonValueRemoteCodec$schema5))])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_1$schema = z.union([z.undefined(), z.string()])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.string().readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema3)), z.array(z.lazy(() => JsonValueRemoteCodec$schema3))]).readonly(),
  'lastMove': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'move': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.string().readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema4)), z.array(z.lazy(() => JsonValueRemoteCodec$schema4))]).readonly(),
  'lastMove': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_1$schema = z.union([z.undefined(), z.object({
  'sessionId': z.string().readonly().optional(),
})])
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.string().readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema2)), z.array(z.lazy(() => JsonValueRemoteCodec$schema2))]).readonly(),
  'lastMove': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
  'side': z.union([z.literal("red"), z.literal("black")]).readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.string().readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema)), z.array(z.lazy(() => JsonValueRemoteCodec$schema))]).readonly(),
  'lastMove': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly().optional(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_0$schema = z.intersection(z.string(), z.unknown())
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_1$schema = z.object({
  'gameId': z.string().readonly(),
  'revision': z.number().readonly(),
})
const _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_result$schema = z.object({
  'gameId': z.string().readonly(),
  'sessionId': z.string().readonly().optional(),
  'revision': z.number().readonly(),
  'phase': z.union([z.literal("active"), z.literal("resigned")]).readonly(),
  'winner': z.union([z.literal("red"), z.literal("black")]).readonly().optional(),
  'gameState': z.union([z.literal(null), z.string(), z.number(), z.literal(false), z.literal(true), z.record(z.string(), z.lazy(() => JsonValueRemoteCodec$schema5)), z.array(z.lazy(() => JsonValueRemoteCodec$schema5))]).readonly(),
  'lastMove': z.object({
  'from': z.string().readonly(),
  'to': z.string().readonly(),
}).readonly().optional(),
})

export const TYPERT = {
  package: '@deepseek-ai/dsh-plugin-xiangqi',
  face: 'host',
  schemas: [
  ],
  invocations: [
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/get',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'get',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_0$schema,
          },
        },
        {
          name: 'gameId',
          wire: 'gameId',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/get:gameId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_get_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/xiangqi-validation/src/host/dsh-service.ts","line":84,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/move',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'move',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiMoveRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_move_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/xiangqi-validation/src/host/dsh-service.ts","line":91,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/newGame',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'newGame',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_0$schema,
          },
        },
        {
          name: '_request',
          wire: '_request',
          source: 'json',
          acceptsUndefined: true,
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiNewGameRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_newGame_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/xiangqi-validation/src/host/dsh-service.ts","line":77,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/resign',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'resign',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiResignRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_resign_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/xiangqi-validation/src/host/dsh-service.ts","line":103,"column":3},
    },
    {
      id: '@deepseek-ai/dsh-plugin-xiangqi#xiangqi/undo',
      service: 'xiangqi',
      namespace: 'xiangqi',
      method: 'undo',
      invocation: { kind: 'direct' },
      scope: {
        context: 'agent',
        wire: 'agentId',
      },
      parameters: [
        {
          name: 'agent',
          wire: 'agentId',
          source: 'lookup',
          lookup: 'agent',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-session/types#SessionId',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_0$schema,
          },
        },
        {
          name: 'request',
          wire: 'request',
          source: 'json',
          codec: {
            mode: 'strict',
            typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiUndoRequest',
            schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_parameter_1$schema,
          },
        },
      ],
      result: {
        mode: 'strict',
        typeSymbol: '@deepseek-ai/dsh-plugin-xiangqi/types#XiangqiSerializedState',
        schema: _deepseek_ai_dsh_plugin_xiangqi_xiangqi_undo_result$schema,
      },
      sourceLocation: {"file":"packages/extensions/xiangqi-validation/src/host/dsh-service.ts","line":97,"column":3},
    },
  ],
  model: {
    "services": [
      {
        "description": "Host-side service loaded by the bundle patch. Every Remote method starts with Agent so Typert maps the client SessionId to the exact live agent.",
        "summary": "Host-side service loaded by the bundle patch.",
        "tags": [],
        "jsDoc": "/**\n * Host-side service loaded by the bundle patch. Every Remote method starts\n * with Agent so Typert maps the client SessionId to the exact live agent.\n */",
        "key": "xiangqi",
        "exportName": "XiangqiService",
        "members": [
          {
            "kind": "method",
            "name": "newGame",
            "signature": "@Remote('newGame') newGame(agent: Agent, _request?: XiangqiNewGameRequest): XiangqiSerializedState",
            "summary": "Start one new game owned by the calling DSH session.",
            "jsDoc": "/** Start one new game owned by the calling DSH session. */"
          },
          {
            "kind": "method",
            "name": "get",
            "signature": "@Remote('get') get(agent: Agent, gameId?: string): XiangqiSerializedState",
            "summary": "Read the requested game, or the session's latest game when omitted.",
            "jsDoc": "/** Read the requested game, or the session's latest game when omitted. */"
          },
          {
            "kind": "method",
            "name": "move",
            "signature": "@Remote('move') move(agent: Agent, request: XiangqiMoveRequest): XiangqiSerializedState",
            "summary": "Apply one revision-fenced move.",
            "jsDoc": "/** Apply one revision-fenced move. */"
          },
          {
            "kind": "method",
            "name": "undo",
            "signature": "@Remote('undo') undo(agent: Agent, request: XiangqiUndoRequest): XiangqiSerializedState",
            "summary": "Undo one committed move.",
            "jsDoc": "/** Undo one committed move. */"
          },
          {
            "kind": "method",
            "name": "resign",
            "signature": "@Remote('resign') resign(agent: Agent, request: XiangqiResignRequest): XiangqiSerializedState",
            "summary": "Mark one side as resigned.",
            "jsDoc": "/** Mark one side as resigned. */"
          },
          {
            "kind": "method",
            "name": "executeTool",
            "signature": "executeTool(agent: Agent, args: XiangqiToolArgs): XiangqiToolResult",
            "summary": "Execute the model tool against the exact agent owning the current turn.",
            "jsDoc": "/** Execute the model tool against the exact agent owning the current turn. */"
          }
        ],
        "types": [
          {
            "name": "Agent",
            "declaration": "export interface Agent {\n    readonly id: SessionId;\n    readonly options: AgentOptions;\n    readonly session: Session;\n    readonly inbox: Inbox;\n    readonly status: AgentStatus;\n    readonly ctx: Context;\n    cancel(cause: AgentCancelCause, options?: CancelOptions): void;\n    whenIdle(): Promise<void>;\n    runMaintenance<T>(task: (signal: AbortSignal) => Promise<T>): Promise<T>;\n    send(message: UserMessage, target: InboxTarget, wakeup: boolean): void;\n    followup(message: UserMessage): void;\n    steer(message: UserMessage): void;\n    inject(message: UserMessage): void;\n}"
          },
          {
            "name": "AgentCancelCause",
            "declaration": "export type AgentCancelCause = { readonly kind: 'user'; } | { readonly kind: 'parent'; } | { readonly kind: 'hook'; readonly reason: string; } | { readonly kind: 'disposed'; };"
          },
          {
            "name": "AgentOptions",
            "declaration": "export interface AgentOptions {\n    provider?: string;\n    model?: string;\n    maxTokens?: number;\n}"
          },
          {
            "name": "AgentStatus",
            "declaration": "export type AgentStatus = 'idle' | 'running';"
          },
          {
            "name": "ApprovalOutcome",
            "declaration": "export type ApprovalOutcome = 'allowed-once' | 'rejected' | 'cancelled' | 'unavailable';"
          },
          {
            "name": "ApprovalPolicy",
            "declaration": "export type ApprovalPolicy = 'ask' | 'never';"
          },
          {
            "name": "ApprovalRequestId",
            "declaration": "export type ApprovalRequestId = Branded<'ApprovalRequestId'>;"
          },
          {
            "name": "AssistantMessage",
            "declaration": "export interface AssistantMessage extends Message {\n    readonly role: 'assistant';\n    readonly source: ModelMessageSource;\n}"
          },
          {
            "name": "AssistantProvenance",
            "declaration": "export interface AssistantProvenance {\n    provider: string;\n    model: string;\n    replayState?: unknown;\n}"
          },
          {
            "name": "AttachmentId",
            "declaration": "export type AttachmentId = Branded<'AttachmentId'>;"
          },
          {
            "name": "Branded",
            "declaration": "export type Branded<B extends string> = string & { readonly [BRAND]: B; };"
          },
          {
            "name": "CallId",
            "declaration": "export type CallId = Branded<'CallId'>;"
          },
          {
            "name": "CancelOptions",
            "declaration": "export interface CancelOptions {\n    keepInbox?: boolean | undefined;\n}"
          },
          {
            "name": "CodeDispatchEventData",
            "declaration": "export interface CodeDispatchEventData extends CodeDispatchStartEventData {\n    isError: boolean;\n    content: ContentBlock[];\n}"
          },
          {
            "name": "CodeDispatchStartEventData",
            "declaration": "export interface CodeDispatchStartEventData {\n    rootCallId: CallId;\n    parentCallId: CallId;\n    subCallId: CallId;\n    name: string;\n    arguments: unknown;\n}"
          },
          {
            "name": "ContentBlock",
            "declaration": "export type ContentBlock = ContentBlockMap[ContentBlockType];"
          },
          {
            "name": "ContentBlockMap",
            "declaration": "export interface ContentBlockMap {\n    text: TextBlock;\n    reasoning: ReasoningBlock;\n    image: ImageBlock;\n    'tool-call': ToolCallBlock;\n    'tool-result': ToolResultBlock;\n}"
          },
          {
            "name": "ContentBlockType",
            "declaration": "export type ContentBlockType = keyof ContentBlockMap;"
          },
          {
            "name": "ContextFormed",
            "declaration": "export type ContextFormed = { readonly form?: never; } | { readonly form: 'instructions'; } | { readonly form: 'catalog'; } | { readonly form: 'snapshot'; readonly sections: readonly ContextSnapshotSection[]; } | { readonly form: 'notice'; readonly summary: string; } | { readonly form: 'relay'; } | { readonly form: 'recall'; };"
          },
          {
            "name": "ContextSnapshotSection",
            "declaration": "export interface ContextSnapshotSection {\n    readonly name: string;\n    readonly text: string;\n}"
          },
          {
            "name": "EpochHeader",
            "declaration": "export interface EpochHeader {\n    config: LlmCallConfig;\n    adapterDefaults?: LlmCallConfigAdapterDefaults;\n    system?: string;\n    tools?: ToolSchema[];\n}"
          },
          {
            "name": "FinishReason",
            "declaration": "export type FinishReason = FinishReasonMap[keyof FinishReasonMap];"
          },
          {
            "name": "FinishReasonMap",
            "declaration": "export interface FinishReasonMap {\n    stop: { kind: 'stop'; };\n    'tool-calls': { kind: 'tool-calls'; };\n    'max-tokens': { kind: 'max-tokens'; };\n    aborted: { kind: 'aborted'; failure: LlmFailure; };\n    error: { kind: 'error'; failure: LlmFailure; };\n}"
          },
          {
            "name": "ImageAttachmentRef",
            "declaration": "export interface ImageAttachmentRef {\n    attachmentId: AttachmentId;\n    mediaType: ImageMediaType;\n    bytes: number;\n    width: number;\n    height: number;\n    name?: string;\n}"
          },
          {
            "name": "ImageBlock",
            "declaration": "export interface ImageBlock {\n    type: 'image';\n    attachment: ImageAttachmentRef;\n}"
          },
          {
            "name": "ImageMediaType",
            "declaration": "export type ImageMediaType = 'image/png' | 'image/jpeg' | 'image/webp' | 'image/gif';"
          },
          {
            "name": "Inbox",
            "declaration": "export class Inbox {\n    get nextTurn(): readonly UserMessage[];\n    get nextStep(): readonly UserMessage[];\n    get hasPending(): boolean;\n    clear(): void;\n    claim(target: InboxTarget, turn: number): UserMessage[];\n    append(target: InboxTarget, message: UserMessage): void;\n    prepend(target: InboxTarget, message: UserMessage): void;\n    replace(messageId: MessageId, newMessage: UserMessage): boolean;\n    remove(messageId: MessageId): boolean;\n    splice(target: InboxTarget, start: number, deleteCount: number, inserted: UserMessage[]): UserMessage[];\n}"
          },
          {
            "name": "InboxTarget",
            "declaration": "export type InboxTarget = 'next-turn' | 'next-step';"
          },
          {
            "name": "JsonObject",
            "declaration": "export interface JsonObject {\n    [key: string]: JsonValue;\n}"
          },
          {
            "name": "JsonPrimitive",
            "declaration": "export type JsonPrimitive = string | number | boolean | null;"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = JsonPrimitive | JsonObject | JsonValue[];"
          },
          {
            "name": "JsonValue",
            "declaration": "export type JsonValue = null | boolean | number | string | JsonValue[] | { [key: string]: JsonValue; };"
          },
          {
            "name": "LlmCallConfig",
            "declaration": "export interface LlmCallConfig {\n    provider: string;\n    model: string;\n    reasoningEffort?: ReasoningEffortId;\n    temperature?: number;\n    maxTokens?: number;\n    stop?: string[];\n}"
          },
          {
            "name": "LlmCallConfigAdapterDefaults",
            "declaration": "export interface LlmCallConfigAdapterDefaults {\n    reasoningEffort?: true;\n    maxTokens?: true;\n}"
          },
          {
            "name": "LlmFailure",
            "declaration": "export interface LlmFailure {\n    readonly message: string;\n    readonly code: string;\n    readonly status?: number;\n    readonly providerRetryAfterMs?: number;\n    readonly requestId?: ProviderRequestId;\n}"
          },
          {
            "name": "Message",
            "declaration": "export interface Message {\n    readonly id: MessageId;\n    readonly role: 'system' | 'user' | 'assistant';\n    readonly content: ContentBlock[];\n    readonly source: MessageSource;\n}"
          },
          {
            "name": "MessageId",
            "declaration": "export type MessageId = Branded<'MessageId'>;"
          },
          {
            "name": "MessageSource",
            "declaration": "export type MessageSource = MessageSourceMap[keyof MessageSourceMap];"
          },
          {
            "name": "MessageSourceMap",
            "declaration": "export interface MessageSourceMap {\n    user: { kind: 'user'; };\n    plugin: { kind: 'plugin'; plugin: string; } & ContextFormed;\n    model: ModelMessageSource;\n    tool: ToolMessageSource;\n}"
          },
          {
            "name": "ModelMessageSource",
            "declaration": "export interface ModelMessageSource extends AssistantProvenance {\n    kind: 'model';\n}"
          },
          {
            "name": "ProviderRequestId",
            "declaration": "export type ProviderRequestId = Branded<'ProviderRequestId'>;"
          },
          {
            "name": "ReasoningBlock",
            "declaration": "export interface ReasoningBlock {\n    type: 'reasoning';\n    text: string;\n}"
          },
          {
            "name": "ReasoningEffortId",
            "declaration": "export type ReasoningEffortId = Branded<'ReasoningEffortId'>;"
          },
          {
            "name": "ReplayEnvelope",
            "declaration": "export interface ReplayEnvelope {\n    response: unknown;\n    blocks?: readonly unknown[];\n}"
          },
          {
            "name": "RequestContext",
            "declaration": "export interface RequestContext {\n    provider: string;\n    model: string;\n    contextWindow?: number;\n}"
          },
          {
            "name": "RequestHeaderReason",
            "declaration": "export type RequestHeaderReason = 'initial' | 'resume' | 'change';"
          },
          {
            "name": "Session",
            "declaration": "export class Session {\n    get surface(): SessionSurface;\n    readonly header: SessionHeader;\n    get id(): SessionId;\n    readonly firstLiveSeq: number;\n    get events(): readonly SessionEvent[];\n    get seq(): number;\n    append<T extends SessionEventType>(type: T, data: SessionEventMap[T], ...opts: T extends SurfaceEventType ? [opts: SurfaceIntent] : []): SessionEvent<T>;\n    requestHeader(): EpochHeader | undefined;\n    requestContext(): RequestContext | undefined;\n    deriveMessages(): Message[];\n    deriveEventMessage(event: SessionEvent): Message | null;\n}"
          },
          {
            "name": "SessionEvent",
            "declaration": "export type SessionEvent<T extends SessionEventType = SessionEventType> = { [K in SessionEventType]: { type: K; seq: number; time: number; data: SessionEventMap[K]; ignorable?: true; } & (K extends SurfaceEventType ? { sourceEventSeqs?: number[]; surfaceOp?: SurfaceOp; } : object) }[T];"
          },
          {
            "name": "SessionEventMap",
            "declaration": "export interface SessionEventMap {\n    'turn/start': { turn: number; };\n    'turn/end': { turn: number; reason: TurnEndReason; };\n    'step/start': { turn: number; step: number; };\n    'step/end': { turn: number; step: number; };\n    'user/message': UserMessage;\n    'assistant/chunk': { turn: number; step: number; chunk: StreamChunk; };\n    'assistant/message': { turn: number; step: number; message: AssistantMessage; usage?: TokenUsage; };\n    'tool/call': { turn: number; step: number; callId: CallId; name: string; arguments: string; };\n    'tool/result': { turn: number; step: number; message: ToolResultMessage; error?: { name: string; code: string; }; meta?: JsonValue; };\n    'todo/write': { todos: TodoItem[]; };\n    'request/header': { header: EpochHeader; reason: RequestHeaderReason; };\n    'request/context': RequestContext;\n    'session/end-seed': Record<string, never>;\n    'agent/inbox/spliced': { target: InboxTarget; start: number; removedCount?: number; inserted: UserMessage[]; outcome?: 'canceled'; };\n    'approval/asked': { id: ApprovalRequestId; toolName: string; callId?: CallId; reason?: string; };\n    'approval/decided': { id: ApprovalRequestId; outcome: ApprovalOutcome; };\n    'approval/policy': { policy: ApprovalPolicy; source?: 'delegation'; };\n    'tool/code-dispatch-start': CodeDispatchStartEventData;\n    'tool/code-dispatch': CodeDispatchEventData;\n    'xiangqi/change': XiangqiChange;\n}"
          },
          {
            "name": "SessionEventType",
            "declaration": "export type SessionEventType = keyof SessionEventMap;"
          },
          {
            "name": "SessionHeader",
            "declaration": "export interface SessionHeader {\n    readonly version: number;\n    readonly id: SessionId;\n    readonly createdAt: number;\n    readonly cwd?: string;\n    readonly parentSession?: SessionId;\n    readonly seedLength?: number;\n    readonly origin?: 'subagent';\n    readonly delegationDepth?: number;\n    readonly agentPreset?: string;\n}"
          },
          {
            "name": "SessionId",
            "declaration": "export type SessionId = Branded<'SessionId'>;"
          },
          {
            "name": "SessionSurface",
            "declaration": "export interface SessionSurface {\n    readonly nodes: readonly number[];\n    readonly replaceGeneration: number;\n}"
          },
          {
            "name": "StreamChunk",
            "declaration": "export type StreamChunk = { type: 'block-start'; index: number; blockType: ContentBlockType; } | { type: 'text-delta'; index: number; text: string; } | { type: 'reasoning-delta'; index: number; text: string; } | { type: 'tool-call-delta'; index: number; id: CallId; name?: string; argumentsDelta: string; } | { type: 'block-end'; index: number; block: ContentBlock; } | { type: 'usage'; usage: TokenUsage; } | { type: 'finish'; reason: FinishReason; replayState?: ReplayEnvelope; };"
          },
          {
            "name": "SurfaceEventType",
            "declaration": "export type SurfaceEventType = 'user/message' | 'assistant/message' | 'tool/result';"
          },
          {
            "name": "SurfaceIntent",
            "declaration": "export interface SurfaceIntent {\n    surfaceOp: SurfaceOp;\n    sourceEventSeqs?: number[];\n}"
          },
          {
            "name": "SurfaceOp",
            "declaration": "export type SurfaceOp = 'append' | { op: 'replace'; start: number; end: number; };"
          },
          {
            "name": "TextBlock",
            "declaration": "export interface TextBlock {\n    type: 'text';\n    text: string;\n}"
          },
          {
            "name": "TodoItem",
            "declaration": "export interface TodoItem {\n    content: string;\n    status: 'pending' | 'in_progress' | 'completed';\n}"
          },
          {
            "name": "TokenUsage",
            "declaration": "export interface TokenUsage {\n    inputTokens: number;\n    outputTokens: number;\n    cacheReadTokens?: number;\n    cacheWriteTokens?: number;\n    reasoningTokens?: number;\n}"
          },
          {
            "name": "ToolCallBlock",
            "declaration": "export interface ToolCallBlock {\n    type: 'tool-call';\n    id: CallId;\n    name: string;\n    arguments: string;\n}"
          },
          {
            "name": "ToolMessageSource",
            "declaration": "export interface ToolMessageSource {\n    kind: 'tool';\n    callId: CallId;\n}"
          },
          {
            "name": "ToolResultBlock",
            "declaration": "export interface ToolResultBlock {\n    type: 'tool-result';\n    toolCallId: CallId;\n    content: ContentBlock[];\n    isError?: boolean;\n}"
          },
          {
            "name": "ToolResultMessage",
            "declaration": "export interface ToolResultMessage extends Message {\n    readonly role: 'user';\n    readonly content: [ToolResultBlock];\n    readonly source: ToolMessageSource;\n}"
          },
          {
            "name": "ToolSchema",
            "declaration": "export interface ToolSchema {\n    name: string;\n    description: string;\n    parameters: Record<string, unknown>;\n}"
          },
          {
            "name": "TurnEndCancelCause",
            "declaration": "export type TurnEndCancelCause = AgentCancelCause | { readonly kind: 'legacy'; };"
          },
          {
            "name": "TurnEndReason",
            "declaration": "export type TurnEndReason = TurnEndReasonMap[keyof TurnEndReasonMap];"
          },
          {
            "name": "TurnEndReasonMap",
            "declaration": "export interface TurnEndReasonMap {\n    completed: { kind: 'completed'; };\n    aborted: { kind: 'aborted'; reason: TurnEndCancelCause; };\n    blocked: { kind: 'blocked'; };\n    error: { kind: 'error'; error: LlmFailure; };\n    'max-tokens': { kind: 'max-tokens'; };\n    interrupted: { kind: 'interrupted'; };\n}"
          },
          {
            "name": "UserMessage",
            "declaration": "export interface UserMessage extends Message {\n    readonly role: 'user';\n}"
          },
          {
            "name": "XiangqiChange",
            "declaration": "export interface XiangqiChange {\n    readonly operation: XiangqiOperation;\n    readonly state: XiangqiSerializedState;\n}"
          },
          {
            "name": "XiangqiGamePhase",
            "declaration": "export type XiangqiGamePhase = 'active' | 'resigned';"
          },
          {
            "name": "XiangqiMove",
            "declaration": "export interface XiangqiMove {\n    readonly from: string;\n    readonly to: string;\n}"
          },
          {
            "name": "XiangqiMoveRequest",
            "declaration": "export interface XiangqiMoveRequest {\n    readonly gameId: string;\n    readonly revision: number;\n    readonly move: XiangqiMove;\n}"
          },
          {
            "name": "XiangqiNewGameRequest",
            "declaration": "export interface XiangqiNewGameRequest {\n    readonly sessionId?: string;\n}"
          },
          {
            "name": "XiangqiOperation",
            "declaration": "export type XiangqiOperation = 'newGame' | 'move' | 'undo' | 'resign';"
          },
          {
            "name": "XiangqiResignRequest",
            "declaration": "export interface XiangqiResignRequest {\n    readonly gameId: string;\n    readonly revision: number;\n    readonly side: XiangqiSide;\n}"
          },
          {
            "name": "XiangqiSerializedState",
            "declaration": "export interface XiangqiSerializedState {\n    readonly gameId: string;\n    readonly sessionId?: string;\n    readonly revision: number;\n    readonly phase: XiangqiGamePhase;\n    readonly winner?: XiangqiSide;\n    readonly gameState: JsonValue;\n    readonly lastMove?: XiangqiMove;\n}"
          },
          {
            "name": "XiangqiSide",
            "declaration": "export type XiangqiSide = 'red' | 'black';"
          },
          {
            "name": "XiangqiToolAction",
            "declaration": "export type XiangqiToolAction = 'new_game' | 'get' | 'move' | 'undo' | 'resign';"
          },
          {
            "name": "XiangqiToolArgs",
            "declaration": "export interface XiangqiToolArgs {\n    readonly action: XiangqiToolAction;\n    readonly game_id?: string;\n    readonly session_id?: string;\n    readonly revision?: number;\n    readonly from?: string;\n    readonly to?: string;\n    readonly side?: XiangqiSide;\n}"
          },
          {
            "name": "XiangqiToolResult",
            "declaration": "export interface XiangqiToolResult {\n    readonly ok: true;\n    readonly action: XiangqiToolAction;\n    readonly state: XiangqiSerializedState;\n    readonly message: string;\n}"
          },
          {
            "name": "XiangqiUndoRequest",
            "declaration": "export interface XiangqiUndoRequest {\n    readonly gameId: string;\n    readonly revision: number;\n}"
          }
        ]
      }
    ],
    "events": [],
    "objects": []
  },
}
